// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZp61OmzvjdkauQYdH-C78xCrczgG9b5Q',
    appId: '1:952519137902:web:21c063b33cb2871ca9647f',
    messagingSenderId: '952519137902',
    projectId: 'biblioteca-5f52d',
    authDomain: 'biblioteca-5f52d.firebaseapp.com',
    storageBucket: 'biblioteca-5f52d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmUKDn3hEbwTMcYcHoq5EHEojawWO26o',
    appId: '1:952519137902:android:3233c241f08da54ba9647f',
    messagingSenderId: '952519137902',
    projectId: 'biblioteca-5f52d',
    storageBucket: 'biblioteca-5f52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYaw1y6CkxCn1TWtMyl3l5Zxrx088RVs',
    appId: '1:952519137902:ios:c65c4a61944bcb31a9647f',
    messagingSenderId: '952519137902',
    projectId: 'biblioteca-5f52d',
    storageBucket: 'biblioteca-5f52d.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYaw1y6CkxCn1TWtMyl3l5Zxrx088RVs',
    appId: '1:952519137902:ios:c65c4a61944bcb31a9647f',
    messagingSenderId: '952519137902',
    projectId: 'biblioteca-5f52d',
    storageBucket: 'biblioteca-5f52d.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZp61OmzvjdkauQYdH-C78xCrczgG9b5Q',
    appId: '1:952519137902:web:bf44972fa0a03e2ea9647f',
    messagingSenderId: '952519137902',
    projectId: 'biblioteca-5f52d',
    authDomain: 'biblioteca-5f52d.firebaseapp.com',
    storageBucket: 'biblioteca-5f52d.firebasestorage.app',
  );
}
